package backend.model.playerDetails;

public enum Position {
    GOALKEEPER, LEFT_BACK, CENTER_BACK, RIGHT_BACK, DEFENSIVE_MIDFIELDER, LEFT_MIDFIELDER, RIGHT_MIDFIELDER,
    ATTACKING_MIDFIELDER, CENTER_FORWARD, STRIKER, LEFT_WINGER, RIGHT_WINGER
}
